services:
  - type: web
    name: job-searcher-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn web.backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
